### ISSUE TITLE
Stream URL Lookup Failing

### ISSUE THREAD

**Issue by judsonmitchell** [hechtus/squeezebox-googlemusic#29]
Thanks for this great plugin!  All was going well until yesterday I started getting error messages like this when loading any content from Google Music:

[14-02-27 07:54:11.3681] Plugins::GoogleMusic::ProtocolHandler::getNextTrack (103) Looking up stream url for url googlemusic:track:Tgcgmzld6oonno3zekevpar745a failed.

The plugin retrieves the track information and artwork, but cannot play.  I have an All Access account.  All other plugins (Rhapsody, Android) are working fine.  Any thoughts?

**Comment by sandeepameba** [comment]
Hi I am also getting error while click on any track get stream url request.The error is response received but request not successful.

**Comment by ErNancy** [comment]
<HTML>
<HEAD>
 <TITLE>Not Found</TITLE>
</HEAD>
 <BODY BGCOLOR="#FFFFFF" TEXT="#000000">
 <H1>Not Found</H1>
 <H2>Error 404</H2>
</BODY>
 </HTML>
 Error parsing data org.json.JSONException: Value <HTML> of type java.lang.String cannot be converted to JSONObject
 I am also getting error while click on any track get stream url request.
