### ISSUE TITLE
Login to Google Play Music failed. Bad username or password.  

### ISSUE THREAD

**Issue by bgeneto** [hechtus/squeezebox-googlemusic#60]
Hello!

I cannot login to my Play Music account! A very strange behavior is happening when I input my Google Play Music All Access username and password in the LMS squeezebox-googlemusic plugin settings page... 

By clicking "Apply" for the very first time, it returns the message: "Not logged in to Google Play Music. Set your username and password." Then, when I click "Apply" again, without changing anything, the same message. If I change my username to a wrong one and click "Apply" I got: "Login to Google Play Music failed. Bad username or password." If now I correct my username and then click "Apply" one more time it gives me the same login failed message (odd)!! The only way that I can successfully login (so it seems) is by checking/unchecking "Disable SSL verification" every time and then clicking the "Apply" button. As a result it returns my "Mobile Device ID" correctly and ask me to restart LMS. But when LMS is up again I'm not connected, see log below: 

Plugins::GoogleMusic::Plugin::initPlugin (99) Not logged in to Google Play Music. Set your username and password.   

Any ideas? What is going on?

PS.: currently using plugin v0.4.0 but also tested with the development version 0.4.1. LMS for  linux v7.9 (nightly).

**Comment by alexanderadam** [comment]
Hey @hechtus, I'm sorry that I have to bother you again regarding this issue:
I have 2-step verification activated but I'm running exactly in the mentioned issue above.
No request appears on my phone.

Are the regular Google Play credentials to be entered?

Do you have any advice on which credentials someone have to enter?

Thank you in advance
