### ISSUE TITLE
Playlist only plays first song

### ISSUE THREAD

**Issue by Drew5316** [hechtus/squeezebox-googlemusic#70]
Logitech Media Server Version: 7.9.0 - 1423576925 @ Wed Feb 11 04:05:18 UTC 2015
Google Music plug-in: v0.4.1

When I start a Playlist in Google Music via my Android phone or via the server webpage (port 9000), it plays the first song fine, but will not play the next song. Only way I've found to get it to "work" is to toggle the software power button on the remote or the server webpage, off then back on again. Annoying to do for every song in a playlist. 

Any thoughts?

Thanks for the great work on the plug-in. When it works (I've used this successfully in a previous installation) it's really awesome.

Drew

**Comment by hechtus** [comment]
Does this only apply to playlists or also for albums and radio stations?

**Comment by Drew5316** [comment]
Yes, behavior is the same on albums and radio, however, I'm getting inconsistent behavior among players. Will research and get back with results. Thanks.

Drew

**Comment by Drew5316** [comment]
Yeah, the inconsistent behavior is still there, but it's definitely occurring enough to be an issue of concern.

**Comment by hechtus** [comment]
You said that it worked in a previous installation. What was the exact version of the LMS and plugin?

Which players (clients) are effected?

**Comment by Drew5316** [comment]
Previous installation (needed to check my notes on my Wiki):
LMS 7.7.3 with gmusicapi 3.1.1 on Linux Mint 16 32-bit, using Squeezelite as the player (unknown version)

Current installation:
LMS: 7.8.1
Google Music Plugin: 0.4.1
Linux Mint 17.1 32-bit
Players: Squeezelite: 1.7 (Linux Mint 17.1 laptop — this is the *important* one), Squeeze Player 1.3.10 (Android Nexus 5), Squeezebox Boom, SqueezePlay 7.8.0r539 (Mac OS X 10.8.3)

So a lot of testing, and not 100% sure, but it seems to be related to if Clementine music player had been active. Quitting Clementine releases the audio port, but LMS behaves very odd — doesn't skip ahead in the song when selecting a different (non-current) location either from the server webpage or Logitech remote. Next song won't play unless "next" is hit or selected from the playlist.

Not sure if there's a process to kill to let LMS regain control or not...?

Best I could do is either remove Clementine entirely or if it's used, I have to reboot to gain full control of LMS, again.

Drew

**Comment by Drew5316** [comment]
After doing a bit of research, it seems to be pointing to how PulseAudio handles the ports, but I can't understand how that would affect LMS...? (I could just be throwing darts, so feel free to stop me.)

Drew

**Comment by Drew5316** [comment]
Is there a procedure for generating a log for recording this odd behavior?

Drew

**Comment by Drew5316** [comment]
I've gone a couple days after removing Clementine and have not had the issue recur.

Drew
