### ISSUE TITLE
Problems with Ubuntu 14.04 on ARM platform?

### ISSUE THREAD

**Issue by ghost** [hechtus/squeezebox-googlemusic#77]
Hi,

I just updated my Odroid U3 to Ubuntu 14.04 (Max2Play Image) and have everything up and running again. Sadly the Google Music Plugin doesn't want to work. I have gmusicapi running again, but for some reason no luck with Googlemusic Plugin. It says "Plugin konnte nicht geladen werden" in the Plugins page and appears to be complaining about "InLine module" in the logs...

Any idea? I never had this issue before.

[15-03-08 20:58:00.8567] Slim::bootstrap::tryModuleLoad (286) Warning: Module [Plugins::GoogleMusic::Plugin] failed to load:
Can't locate Inline.pm in @INC (you may need to install the Inline module) (@INC contains: /var/lib/squeezeboxserver/cache/InstalledPlugins /usr/share/squeezeboxserver/CPAN/arch/5.18/arm-linux-gnueabihf-thread-multi-64int /usr/share/squeezeboxserver/CPAN/arch/5.18/arm-linux-gnueabihf-thread-multi-64int/auto /usr/share/squeezeboxserver/CPAN/arch/5.18.2/arm-linux-gnueabihf-thread-multi-64int /usr/share/squeezeboxserver/CPAN/arch/5.18.2/arm-linux-gnueabihf-thread-multi-64int/auto /usr/share/squeezeboxserver/CPAN/arch/5.18/arm-linux-gnueabihf-thread-multi-64int /usr/share/squeezeboxserver/CPAN/arch/5.18/arm-linux-gnueabihf-thread-multi-64int/auto /usr/share/squeezeboxserver/CPAN/arch/arm-linux-gnueabihf-thread-multi-64int /usr/share/squeezeboxserver/CPAN/arch/5.18 /usr/share/squeezeboxserver/lib /usr/share/squeezeboxserver/CPAN /usr/share/squeezeboxserver /usr/share/squeezeboxserver/CPAN /usr/share/squeezeboxserver /usr/sbin /etc/perl /usr/local/lib/perl/5.18.2 /usr/local/share/perl/5.18.2 /usr/lib/perl5 /usr/share/perl5 /usr/lib/perl/5.18 /usr/share/perl/5.18 /usr/local/lib/site_perl .) at /var/lib/squeezeboxserver/cache/InstalledPlugins/Plugins/GoogleMusic/GoogleAPI.pm line 73.
BEGIN failed--compilation aborted at /var/lib/squeezeboxserver/cache/InstalledPlugins/Plugins/GoogleMusic/GoogleAPI.pm line 73.
Compilation failed in require at /var/lib/squeezeboxserver/cache/InstalledPlugins/Plugins/GoogleMusic/Settings.pm line 20.
BEGIN failed--compilation aborted at /var/lib/squeezeboxserver/cache/InstalledPlugins/Plugins/GoogleMusic/Settings.pm line 20.
Compilation failed in require at /var/lib/squeezeboxserver/cache/InstalledPlugins/Plugins/GoogleMusic/Plugin.pm line 24.
BEGIN failed--compilation aborted at /var/lib/squeezeboxserver/cache/InstalledPlugins/Plugins/GoogleMusic/Plugin.pm line 24.
Compilation failed in require at (eval 1071) line 1.
BEGIN failed--compilation aborted at (eval 1071) line 1.

[15-03-08 20:58:00.8586] Slim::Utils::PluginManager::load (323) Error: Couldn't load Plugins::GoogleMusic::Plugin

**Comment by ghost** [comment]
Fixed by following #69

**Comment by hechtus** [comment]
Could you please tell us the exact commands you where using to solve this issue?

**Comment by ghost** [comment]
sudo cpan App::cpanminus
 sudo cpanm --notest Inline
 sudo cpanm --notest Inline::Python

Those commands from the OS-X issue. However, I had to run them twice for some reason.

**Comment by hechtus** [comment]
OK. Thanks for clarifying.
