### ISSUE TITLE
Radio doesn't play

### ISSUE THREAD

**Issue by Tbower** [hechtus/squeezebox-googlemusic#78]
Logitech Media Server Version: 7.8.1 - 1407915121 @ Sat Aug 16 03:00:00 UTC 2014
Ubuntu 14.04.2 LTS
Google Music 0.4.1

Been using this plugin for awhile, and it has worked well.

At some point (sadly, I can't say exactly when, but probably after my last LMS upgrade, or maybe after Ubuntu maintenance), All Access radio stopped working.  This happens regardless of the player used (Duet, Squeezeplay, Android...doesn't matter).  It also happens with my radio stations, "I'm Feeling Lucky Radio", or any Genre stations.

Any time I try to play radio, the server log shows the following:

[15-03-13 11:05:55.0553] Plugins::GoogleMusic::Radio::fetchStationTracks (436) Not able to get tracks for station 3761e87e-1fee-341e-bee5-d5145c5c6a1c: exceptions.TypeError: get_station_tracks() takes at most 3 arguments (4 given) at (eval 1016) line 170.

**Comment by hechtus** [comment]
You should definitely try to update gmusicapi to the latest dev version. Thanks for being so specific. The log file snippet helped to identify the problem.

**Comment by Tbower** [comment]
That took care of it!  All is well now.

Thanks for the quick reply hechtus!

**Comment by hechtus** [comment]
You're welcome! Thanks for reporting.
