### ISSUE TITLE
Installed on Raspberry PI but unable to login to Google

### ISSUE THREAD

**Issue by eskdale** [hechtus/squeezebox-googlemusic#96]
I've installed it fine and the plugin seems to be working but no matter how I try I can't login
I always get "Login to Google Play Music failed. Bad username or password.  "
I've tried 2 different accounts 1 with 2 factor authentication using an app password and another without 2 factor - Have spent many hours seems a shame to give up when so close
Any ideas would be appreciated.  Is it me or is it Google.

![image](https://cloud.githubusercontent.com/assets/3305160/13554196/8cdc5b86-e399-11e5-846e-a2dcc69fefe6.png)

Did just find this in the log
[16-03-06 13:05:59.6396] Plugins::GoogleMusic::Plugin::initPlugin (94) Not able to login to Google Play Music: exceptions.TypeError: login() takes exactly 4 arguments (3 given) at (eval 859) line 182.
[16-03-06 13:05:59.6425] Plugins::GoogleMusic::Plugin::initPlugin (99) Not logged in to Google Play Music. Set your username and password.

Fixed now thanks
using
http://nick7634.github.io/squeezebox-googlemusic/repository/repo.xml
sudo pip uninstall gmusicapi
sudo install gmusicapi
and sudo pip install git+https://..................

Pity the main readme couldn't be updated would have saved me a lot of time and probably others
But Hey Thanks to all for the work put into this - awesome. And thanks Nick

**Comment by mark-e-mark** [comment]
This could be the security issue that I saw. Try allowing some applications to log into your Google Account insecurely, as [described in the Google support article](https://support.google.com/accounts/answer/6010255?hl=en).

**Comment by eskdale** [comment]
Thanks Mark - I think my problem was the change of the login parameters I think it was probably Nick's repo.xml that fixed it.  Have now built two servers one for my father and one for myself - both are working now although have seen the login fail but worked on a restart of the LMS service.  Just a pity the main readme is not updated.
